version: '3'
services:
  web:
    image: ruby:3.2.5
    command: bash -c "bundle install && rails server -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    working_dir: /myapp
